# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|

  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"
  config.vm.boot_mode = :headless
  config.vm.forward_port 80, 8080
  config.vm.forward_port 443, 4443
  config.vm.forward_port 22, 2222
  config.vm.share_folder "www", "/home/vagrant/www", "../"

  config.vm.customize ["modifyvm", :id, "--memory", "2048"]
  config.vm.customize ["modifyvm", :id, "--cpus", "1"]

  config.vm.provision :puppet, :options => "--no-report" do |puppet|
    puppet.manifests_path = "puppet"
    puppet.manifest_file  = "main.pp"
    puppet.module_path    = "puppet/modules"
  end
end